import HeaderTop from "../components/HeaderTop";
import Navbar from "../components/Navbar";
import HeaderMain from "../components/HeaderMain";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HeaderTop />
      <HeaderMain />
      <Navbar />

      {children}
    </>
  );
}
